spring:
  datasource:
    url: jdbc:h2:mem:testDB
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  cache:
    cache-names: cacheName,someOtherCacheName
    caffeine:
      spec: initialCapacity=50,maximumSize=10,expireAfterAccess=300s

management:
  endpoints:
    web:
      exposure:
        include: "*"
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
        cache:
          instrument: true

server:
  port: 4455
